COURSE_ACTS(COURSE_BOB, _(" 1 CAMPO DE LOS BOB-OMBAS"),
       _("REY BOB-OMBA EN LA CIMA")     , _("EL RETO DE KOOPA EL RÁPIDO") , _("LANZADO HACIA LA ISLA FLOTANTE"),
       _("EN BUSCA DE LAS 8 MONEDAS ROJAS")          , _("EL VUELO DE MARIO")        , _("DA RIENDA SUELTA A CHOMP CADENAS"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALEZA DE ROCO"),
       _("DERROCA A ROCO")        , _("EN LO MÁS ALTO DE LA FORTALEZA")    , _("LANZADO HACIA EL CIELO"),
       _("MONEDAS ROJAS EN LA ISLA FLOTANTE"), _("CAÍDA LIBRE EN LA ISLA DE LA JAULA")    , _("A CAÑONAZOS CONTRA EL MUR"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAHÍA DEL CAPITÁN"),
       _("EL BOTÍN DEL BARCO HUNDIDO")    , _("LA MORENA LA VIGILA") , _("TESORO EN LA CUEVA DEL OCÉANO"),
       _("MONEDAS ROJAS COMO PERLAS DEL MAR")  , _("APUNTA A LO ALTO DE LA AGUJA")     , _("QUE NO TE LLEVE LA CORRIENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTAÑA HELADA"),
       _("AL FINAL DEL TOBOGÁN")             , _("PEQUEÑO PINGÜINO PERDIDO")             , _("CARRERA CON EL GRAN PINGÜINO"),
       _("MONEDAS ROJAS EN LA MONTAÑA")  , _("MUÑECO DE NIEVE SIN CABEZA")       , _("PATADAS EN LA PARED SON PRÁCTICAS"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANSIÓN DE GRAN BÚ"),
       _("CAZAFANTASMAS")            , _("EL CARRUSEL DEL GRAN BÚ") , _("EL SECRETO QUE GUARDAN LOS LIBROS"),
       _("LAS 8 ENDIABLADAS MONEDAS ROJAS")          , _("EL BALCÓN DEL GRAN BÚ")             , _("¡OJO EN LA HABITACIÓN SECRETA!"))

COURSE_ACTS(COURSE_HMC, _(" 6 CUEVA DEL LABERINTO"),
       _("EL MONSTRUO DE LA CUEVA DEL LAGO")  , _("EL CAMINO DE LAS 8 MONEDAS ROJAS")       , _("¡MARIO, EL HOMBRE DE HIERRO!"),
       _("EN EL LABERINTO TÓXICO")     , _("LA OTRA SALIDA DEL LABERINTO")     , _("MÁS ALLÁ DE LAS BOLAS DE PIEDRA"))

COURSE_ACTS(COURSE_LLL, _(" 7 TIERRA DEL FUEGO"),
       _("LAVA AL GRAN BRONCO")            , _("TRES TRISTES BRONCOS")             , _("EL PUZLE DE LAS 8 MONEDAS"),
       _("¡TRONCO, CÓMO QUEMA!")           , _("EN EL CORAZÓN DEL VOLCÁN")  , _("ESCALADA EN EL VOLCÁN"))

COURSE_ACTS(COURSE_SSL, _(" 8 ARENAS ARDIENTES"),
       _("EN LAS GARRAS DEL PAJARRACO") , _("EN LO ALTO DE LA PIRÁMIDE")      , _("EL SECRETO DE LA PIRÁMIDE"),
       _("CORONA LOS CUATRO PILARES"), _("MONEDAS ROJAS EN VUELO LIBRE")   , _("LABERINTO DE LA PIRÁMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 GRAN MUELLE"),
       _("EL SUBMARINO DE BOWSER")            , _("COFRES EN LA CORRIENTE")         , _("MONEDAS ROJAS, POSTE A POSTE"),
       _("ATRAVESANDO LA CORRIENTE")        , _("TRAS LA ESTELA DE LA MANTA")        , _("CONSIGUE LAS GORRAS..."))

COURSE_ACTS(COURSE_SL, _("10 PAÍS DE NIEVE"),
       _("SOBRE LA CABEZA DEL MUÑECO")            , _("EL DUELO DEL HIELO")          , _("DENTRO DEL HIELO"),
       _("MÁS ALLÁ DEL LAGO HELADO")  , _("CAPARAZÓN PARA MONEDAS ROJAS") , _("EN EL IGLÚ"))

COURSE_ACTS(COURSE_WDW, _("11 CIUDAD ESPONJA"),
       _("¡MOJANDO PLATAFORMAS!")         , _("EN LO MÁS ALTO DE LA CIUDAD")               , _("ENIGMA DE LOS NUMEROS SECRETOS"),
       _("ASCENSOR EXPRESO: ¡DATE PRISA!")   , _("EL ROJO BRILLO DE LA CIUDAD")      , _("EN LA PARTE BAJA DE LA CIUDAD"))

COURSE_ACTS(COURSE_TTM, _("12 MONTAÑA ESCARPADA"),
       _("ESCALA LA MONTAÑA")            , _("EL MISTERIO DE LA JAULA DEL MONO")    , _("MONEDAS ROJAS EN LOS CHAMPIÑONES"),
       _("EL TOBOGÁN MISTERIOSO")       , _("DETRÁS DE LA CASCADA") , _("DISPARADO AL CHAMPIÑÓN SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 ISLA PEQUE-GRANDE"),
       _("SIN MIEDO CONTRA LAS FLORES PIRAÑAS")      , _("EN LO ALTO DE LA ISLA GRANDE"), _("REVANCHA CONTRA KOOPA EL RÁPIDO"),
       _("CINCO DIMINUTOS SECRETOS")       , _("LAS MONEDAS ROJAS DE FLORUGA")           , _("DALE A FLORUGA UNA LECCIÓN"))

COURSE_ACTS(COURSE_TTC, _("14 RELOJ TICTAC"),
       _("RODAMIENTOS EN LA JAULA")            , _("EL POZO Y LOS PÉNDULOS")     , _("UNA MANILLA, POR FAVOR"),
       _("PISA DON PISOTÓN")           , _("LAS BARRAS Y BARRERAS DEL TIEMPO")    , _("PARA EL TIEMPO DE MONEDAS ROJAS"))

COURSE_ACTS(COURSE_RR, _("15 CAMINO DEL ARCO IRIS"),
       _("MASCARÓN ESTELAR")  , _("EL CASÓN CELESTIAL")      , _("LAS MONEDAS DEL LABERINTO VERTICAL"),
       _("DESPUÉS DEL VAIVÉN")        , _("¡TRIÁNGULOS MORTALES!")             , _("EN ALGÚN LUGAR DEL ARCO IRIS"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER EN LAS TINIEBLAS"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER EN EL MAR DE FUEGO"))
SECRET_STAR(COURSE_BITS, _("   BOWSER EN EL CIELO"))
SECRET_STAR(COURSE_PSS, _("   EL TOBOGÁN DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   MINA DE LA GORRA DE HIERRO"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DE LA GORRA ALADA"))
SECRET_STAR(COURSE_VCUTM, _("   INVISIBLE BAJO EL FOSO"))
SECRET_STAR(COURSE_WMOTR, _("   MÁS ALLÁ DEL ARCO IRIS"))
SECRET_STAR(COURSE_SA, _("   EL ACUARIO SECRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELLAS SECRETAS"))

EXTRA_TEXT(0, _("¡UNA DE LAS ESTRELLAS SECRETAS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
