#ifndef _MARIO_GEO_SWITCH_CASE_IDS_H
#define _MARIO_GEO_SWITCH_CASE_IDS_H

/* Mario Geo-Switch-Case IDs */

enum IsabelleEyesGSCId
{
    /*0x00*/ ISABELLE_EYES_BLINK,
    /*0x01*/ ISABELLE_EYES_OPEN,
    /*0x02*/ ISABELLE_EYES_HALF_CLOSED,
    /*0x03*/ ISABELLE_EYES_CLOSED,
    /*0x04*/ ISABELLE_EYES_ANGRY,
    /*0x05*/ ISABELLE_EYES_SAD,
    /*0x06*/ ISABELLE_EYES_HAPPY,
    /*0x07*/ ISABELLE_EYES_SUPRISED,
    /*0x08*/ ISABELLE_EYES_WORRIED,
    /*0x09*/ ISABELLE_EYES_VERY_SURPRISED,
    /*0x0A*/ ISABELLE_EYES_DIZZY
};

enum IsabelleMouthGSCId
{
    /*0x00*/ ISABELLE_MOUTH_CLOSED,
    /*0x01*/ ISABELLE_MOUTH_SMILE,
    /*0x02*/ ISABELLE_MOUTH_BIG_SMILE,
    /*0x03*/ ISABELLE_MOUTH_SAD,
    /*0x04*/ ISABELLE_MOUTH_OPEN,
    /*0x05*/ ISABELLE_MOUTH_VERY_OPEN
};

enum MarioHandGSCId
{
    /*0x00*/ MARIO_HAND_FISTS,
    /*0x01*/ MARIO_HAND_OPEN,
    /*0x02*/ MARIO_HAND_PEACE_SIGN,
    /*0x03*/ MARIO_HAND_HOLDING_CAP,
    /*0x04*/ MARIO_HAND_HOLDING_WING_CAP,
    /*0x05*/ MARIO_HAND_RIGHT_OPEN
};

enum MarioCapGSCId
{
    /*0x00*/ MARIO_HAS_DEFAULT_CAP_ON,
    /*0x01*/ MARIO_HAS_DEFAULT_CAP_OFF,
    /*0x02*/ MARIO_HAS_WING_CAP_ON,
    /*0x03*/ MARIO_HAS_WING_CAP_OFF // unused
};

enum MarioGrabPosGSCId
{
    /*0x00*/ GRAB_POS_NULL,
    /*0x01*/ GRAB_POS_LIGHT_OBJ,
    /*0x02*/ GRAB_POS_HEAVY_OBJ,
    /*0x03*/ GRAB_POS_BOWSER
};


#endif /* _MARIO_GEO_SWITCH_CASE_IDS_H */
